// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giwhavifgfvbmktvzaqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpd2hhdmlmZ2Z2Ym1rdHZ6YXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTMyODUsImV4cCI6MjA2NzU4OTI4NX0.iVqeMrIZxQxvcgdOxbn4qaw9Kt23ikX2TYcZ7sxSj-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});